DFUNK/Models/Payments.cs
namespace DFUNK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Payments
    {
        [Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int payment_id { get; set; }

        [Column(TypeName = "date")]
        public DateTime? date { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? amount { get; set; }

        [StringLength(10)]
        public string payment_method { get; set; }

        public int contact_id { get; set; }

        public int? project_id { get; set; }

        public virtual Contact Contact { get; set; }

        public virtual PaymentMethod PaymentMethod { get; set; }

        public virtual Projects Projects { get; set; }
        
    }
}

DFUNK/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DFUNK.Models;

namespace DFUNK.Controllers
{
    public class PaymentsController : Controller
    {
        private Models.DFUNK db = new Models.DFUNK();

        // GET: Payments
        //public ActionResult Index()
        //{
        //    var payments = db.Payments.Include(p => p.Contact).Include(p => p.PaymentMethod).Include(p => p.Projects);
        //    var result = payments.ToList();
        //    decimal total = 0;
        //    foreach(Payments payment in result)
        //    {
        //        total = total + (decimal)payment.amount;
        //    }

        //    return View(result);
        //}

        public ActionResult Index(int? contact_id)
        {
            var payments = db.Payments.Include(p => p.Contact).Include(p => p.PaymentMethod).Include(p => p.Projects);

            if (contact_id != null)
            {
                payments = payments.Where(x => x.contact_id == contact_id);
                decimal total = 0;
                foreach (Payments payment in payments)
                {
                    total = total + (decimal)payment.amount;
                    ViewBag.TotalAmount = "Total amount paid: " + total.ToString("F");
                    ViewBag.ShowAll = true;
                }
            }
            else
                ViewBag.ShowAll = false;           

            return View(payments.ToList());
        }

        // GET: Payments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        //public ActionResult ShowOneContact(int contact_id)
        //{
        //    var payments = db.Payments.Include(p => p.Contact).Include(p => p.PaymentMethod).Include(p => p.Projects).Where(x => x.contact_id == contact_id);
        //    var result = payments.ToList();
        //    decimal total = 0;
        //    foreach (Payments payment in result)
        //    {
        //        total = total + (decimal)payment.amount;
        //    }

        //    return RedirectToAction("Index", new { id = contact_id });
        //}

        // GET: Payments/Create
        public ActionResult Create()
        {
            ViewBag.contact_id = new SelectList(db.Contact, "contact_id", "name");
            ViewBag.payment_method = new SelectList(db.PaymentMethod, "paymentMethod_id", "name");
            ViewBag.project_id = new SelectList(db.Projects, "project_id", "name");
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "payment_id,date,amount,payment_method,contact_id,project_id")] Payments payments)
        {
            if (ModelState.IsValid)
            {
                payments.date = DateTime.Now;
                db.Payments.Add(payments);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.contact_id = new SelectList(db.Contact, "contact_id", "name", payments.contact_id);
            ViewBag.payment_method = new SelectList(db.PaymentMethod, "paymentMethod_id", "name", payments.payment_method);
            ViewBag.project_id = new SelectList(db.Projects, "project_id", "name", payments.project_id);
            return View(payments);
        }

        // GET: Payments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            ViewBag.contact_id = new SelectList(db.Contact, "contact_id", "name", payments.contact_id);
            ViewBag.payment_method = new SelectList(db.PaymentMethod, "paymentMethod_id", "name", payments.payment_method);
            ViewBag.project_id = new SelectList(db.Projects, "project_id", "name", payments.project_id);
            return View(payments);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "payment_id,date,amount,payment_method,contact_id,project_id")] Payments payments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.contact_id = new SelectList(db.Contact, "contact_id", "name", payments.contact_id);
            ViewBag.payment_method = new SelectList(db.PaymentMethod, "paymentMethod_id", "name", payments.payment_method);
            ViewBag.project_id = new SelectList(db.Projects, "project_id", "name", payments.project_id);
            return View(payments);
        }

        // GET: Payments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Payments payments = db.Payments.Find(id);
            db.Payments.Remove(payments);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DFUNK/Views/Payments/Create.cshtml
@model DFUNK.Models.Payments

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payments</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.payment_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.payment_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.payment_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.payment_method, "payment_method", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("payment_method", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.payment_method, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact_id, "contact_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("contact_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.contact_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.project_id, "project_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("project_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.project_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DFUNK/Views/Payments/Delete.cshtml
@model DFUNK.Models.Payments

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contact.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentMethod.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentMethod.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Projects.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Projects.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DFUNK/Views/Payments/Details.cshtml
@model DFUNK.Models.Payments

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Payments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contact.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentMethod.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentMethod.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Projects.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Projects.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.payment_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DFUNK/Views/Payments/Edit.cshtml
@model DFUNK.Models.Payments

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payments</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.payment_id)

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.payment_method, "payment_method", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("payment_method", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.payment_method, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact_id, "contact_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("contact_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.contact_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.project_id, "project_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("project_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.project_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DFUNK/Views/Payments/Index.cshtml
@model IEnumerable<DFUNK.Models.Payments>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@{
    if (ViewBag.ShowAll)
    {
        <p>
            @Html.ActionLink("Show All", "Index")
        </p>
    }
}
<p>
    @ViewBag.totalAmount
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Contact.name)
        </th>
        <th>
            @Html.DisplayName("Payment Method")
            @*@Html.DisplayNameFor(model => model.PaymentMethod.name)*@
        </th>
        <th>
            @Html.DisplayName("Project")
            @*@Html.DisplayNameFor(model => model.Projects.name)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.amount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="@Url.Action("Index", "Payments", new { contact_id = item.contact_id })">
                <span class="donor">
                @Html.DisplayFor(modelItem => item.Contact.name)
                @Html.DisplayFor(modelItem => item.Contact.surname)</span>
            </a>
            @*@Html.DisplayFor(modelItem => item.Contact.name)
            @Html.DisplayFor(modelItem => item.Contact.surname)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentMethod.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Projects.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.payment_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.payment_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.payment_id })
        </td>
    </tr>
}
</table>